version: '3'

services:
  web:
    build: .
    # image: proxy-utils-web:0.1.0
    image: proxy-utils-web:latest
    container_name: proxy-web
    restart: unless-stopped
    ports:
      # change `5000` into the port to visit
      - "5000:80"
    volumes:
      - .:/app
    environment:
      # if the environment variable is not set, it will use the default value in the config.yml
      - RUN_ENV=production
      - DEBUG=true


