name: Check

on:
  - push
  - pull_request

jobs:
  docker:
    name: Check Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.10'

      - name: Test Docker Build
        run: docker build -t proxy-utils-web .